[package]
name = "doken"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = { version = "1.0.85" }
clap = { version = "3.2.17", features = ["derive"] }
tokio = { version = "1.20.1", features = ["full"] }
tiny_http = "0.11.0"
home = "0.5.3"
url = "2.2.2"
async-trait = "0.1.57"
mime = "0.3.16"
oauth2 = { version = "4.2.3", features = ["reqwest"] }
