[package]
name = "doken"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.136", features = ["derive"] }
clap = { version = "3.1.8", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }
tiny_http = "0.11"
url = "2.2.2"
mime = "0.3.16"
oauth2 = { version = "4.1.0", features = ["reqwest"]}
